# Generated by Django 5.1.7 on 2025-03-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('decision_date', models.DateField()),
                ('full_text', models.TextField()),
                ('ponente', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
            ],
        ),
    ]
