# Generated by Django 5.1.7 on 2025-04-11 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_alter_case_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_text', models.TextField()),
                ('external_link', models.CharField(blank=True, max_length=255, null=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=255, null=True)),
                ('pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('treatment', models.CharField(choices=[('cited', 'CITED'), ('discussed', 'DISCUSSED'), ('criticized', 'CRITICIZED'), ('overruled by law', 'OVERRULED BY LAW'), ('overruled', 'OVERRULED')], max_length=50)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='case.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='practice_area',
            field=models.ManyToManyField(blank=True, to='case.practicearea'),
        ),
    ]
