# Generated by Django 5.1.7 on 2025-04-11 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_practicearea_citation_case_practice_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='preceding_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.case'),
        ),
    ]
